---
- name: check version of app code on app server
  hosts: "tag_Name_phoenix14_base_{{ env }}_app"
  pre_tasks:
    - name: load env-specific vars
      include_vars: "{{ item }}.yml"
      with_items:
        - "{{ env }}"
        - "{{ env }}.vault"
      tags: ["always"]
  tasks:
    - name: stat current code directory
      stat: path="{{ site_dir }}"
      register: site_dir_stat

    - debug: msg="{{ site_dir_stat.stat.lnk_source | basename }}"
