---
- name: deploy application
  hosts: "tag_Name_phoenix14_base_{{ env }}_app"
  become: true
  become_user: "{{ deploy_user }}"
  vars:
    repo_url: https://github.com/pgrunwald/phoenix14_base
    git_branch: master
    work_dir: "{{ repo_dir }}"
    asdf_base_dir: "/opt/asdf"
    path_with_asdf: "{{ asdf_base_dir }}/bin:{{ asdf_base_dir }}/shims:{{ ansible_env.PATH }}"
    erlang_releases_base_dir: "{{ work_dir }}/_build/release/rel/{{ app_name }}/releases"
    mix_env: release
    root_user: root
    git_release_commit_command: "git rev-parse --short {{ git_branch }}"
    tmp_directories: []
    common_env:
      PATH: "{{ path_with_asdf }}"
      MIX_ENV: "{{ mix_env }}"
      ENV: "{{ env }}"
    mix_tasks:
      - "deps.get --only {{ env }}"
      - "deps.clean --unused"
      - compile
    pre_build_commands: []
    node_modules_relative_parent_dir: "assets"
    asset_build_command: 
    release_tasks:
      - migrate
  pre_tasks:
    - name: load env-specific vars
      include_vars: "{{ item }}.yml"
      with_items:
        - "{{ env }}"
        - "{{ env }}.vault"
      tags: ["always"]
  tasks:
    - name: include deploy tasks
      include_tasks: "tasks/elixir-deploy.yml"
      tags: ["always"]

- name: restart application
  hosts: "tag_Name_phoenix14_base_{{ env }}_app"
  become: true
  serial: 1
  tasks:
    - name: restart application
      service: name="{{ app_name }}" state=restarted

    - name: pause to allow application to start accepting requests
      pause: seconds=5
