---
- name: update app servers
  hosts: "{{ env }}_phoenix14_base_app_network_security_group"
  pre_tasks:
    - name: load env-specific vars
      include_vars: "{{ item }}.yml"
      with_items:
        - "{{ env }}"
        - "{{ env }}.vault"
      tags: ["always"]
  roles:
    - elixir-app
    - phoenix14_base-app
