---
- name: update app servers
  hosts: "tag_Name_phoenix14_base_{{ env }}_app"
  pre_tasks:
    - name: load env-specific vars
      include_vars: "{{ item }}.yml"
      with_items:
        - "{{ env }}"
        - "{{ env }}.vault"
      tags: ["always"]
  roles:
    - elixir-app
    - phoenix14_base-app
